name: live_chat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  another_flushbar: ^1.12.30
  dio: ^4.0.6
  cached_network_image: ^3.3.0
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.5
  flutter_svg: ^2.0.9
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_messaging: ^14.7.4
  google_sign_in: ^6.1.6
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  modal_bottom_sheet: ^3.0.0-pre
  pin_code_fields: ^8.0.1
  badges: ^3.1.2
  url_launcher: ^6.2.2
  awesome_dialog: ^3.2.0
  change_app_package_name: ^1.1.0
  model_viewer_plus: ^1.7.2
  tflite_v2: ^1.0.0
  webview_flutter: ^4.7.0
  firebase_storage: ^11.5.1
  google_maps_flutter: ^2.6.1
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env.development
    - .env.production
    - assets/female_person.glb
    - assets/label.txt
    - assets/model.tflite



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Arabic Black 900.otf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-Arabic ExtraBold 800.otf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Arabic Bold 700.otf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Arabic SemiBold 600.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Arabic Medium 500.otf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Arabic Regular 400.otf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Arabic Light 300.otf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Arabic ExtraLight 275.otf
          weight: 200


    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200